### ISSUE TITLE
Issue with multiple accounts

### ISSUE THREAD

**Issue by tomfulghum** [evansloan/collection-log#10]
As I see it the plugin does not differentiate between OSRS accounts, which means the new item message does not show up if another account had already gotten that item before. Is it possible to separate different accounts' collection log data?

**Comment by evansloan** [comment]
Huh, when I originally tested the plugin with two accounts, I did not seem to have any issues when it differentiating between the two. I guess I've made a couple changes since then that may have broken that functionality, I'll look into it this weekend.

**Comment by tomfulghum** [comment]
I'm not ruling out error on my part. I might have missed a page when i initially opened the log, ill check again.

**Comment by tomfulghum** [comment]
The error was on my side, apparently i missed a page.
