### ISSUE TITLE
Plugin auto-update doesn't work on Jagex Launcher Runelite

### ISSUE THREAD

**Issue by RosalinaOS** [evansloan/collection-log#18]
When logging out with upload to collectionlog.net selected on Jagex Launcher-launched Runelite, the website displays either no collection log data, or someone else's collection log data entirely, under my RSN. This is immediately fixed by just using normal Runelite, however

**Comment by evansloan** [comment]
Should be fixed once [v2.2.2](https://github.com/runelite/plugin-hub/pull/2804) update is approved

**Comment by evansloan** [comment]
Resolved
