### ISSUE TITLE
Allow !log command to work locally without connection to collectionlog.net

### ISSUE THREAD

**Issue by dillydill123** [evansloan/collection-log#23]
Is it possible to use the local collection log data in game for the !log command?

**Comment by chrisjben** [comment]
Should be possible. Just have to store the data locally and then reference it locally. Not sure why they decided to do it with an API that's down 80% of the time.

**Comment by evansloan** [comment]
> Should be possible. Just have to store the data locally and then reference it locally. Not sure why they decided to do it with an API that's down 80% of the time.

Unless you want the collection log data of every player that uses the site/plugin stored locally.

The !log command message is built client-side. So when a random player at the GE uses !log, all the other players that have the plugin installed have to get the log data from somewhere, which would be the API. It's not possible to just grab the data locally from that player's computer and broadcast it for all the other players at the GE to see, unless all those other players also have the command issuer's collection log data locally. I'd rather iron out the kinks on the API than to create a mess of random player's collection log data on people's computers on the off chance someone will use the !log command.
