### ISSUE TITLE
Unable to update log entries for new wilderness bosses

### ISSUE THREAD

**Issue by PolsonTerror** [evansloan/collection-log#28]
When first using the plug-in, it asks you to click through the collection logs, but this cannot be done for Callisto, Venenatis & Vet'ion, as their collection logs names changed due to the new wilderness update.

**Comment by many360** [comment]
After some digging i found that the config for collectionlog tabs resides in https://gist.github.com/evansloan/24179c0fbfb370ce162f69dde36d72f0#file-collection_log_template-json.
It's seems that @evansloan tried to fix this issue two weeks ago, but reversed his commit.
I'm not sure why, but both old (Callisto, Venenatis, Vet'ion) and new (Callisto and Artio, Venenatis and Spindel, Vet'ion and Calvar'ion) collection log tabs seem to be necessary as collection log entries before the log can be saved and progress can be tracked.

**Comment by evansloan** [comment]
Not having the old wilderness boss pages should not affect being able to upload data. The displaying of these bosses in the side panel will be fixed in an upcoming update.

> It's seems that @evansloan tried to fix this issue two weeks ago, but reversed his commit.
I'm not sure why

There's code in the plugin to remove outdated pages from players' saved data if the pages no longer exist in that gist you linked. This functionality was added on the off chance that Jagex would for some reason remove a page and was never tested to see if it actually worked (I didn't actually think they would ever remove pages lol). 

So when I initially removed the old bosses from that gist, an error got thrown when trying to remove the pages from the players' save data preventing the plugin from uploading data to the site. I was kind of in a rush to get everything working on the site for the new game update so I just reverted that commit.

**Comment by kschmanski** [comment]
It seems like it only affects users who have never used the plugin before - the user is prompted to open the Collection log for Callisto, Venenatis and Vet'ion before progress can be tracked.

![image](https://user-images.githubusercontent.com/29218137/219815003-02eb943e-5c08-457e-9274-eb07daf5a98c.png)

**Comment by jdwile** [comment]
@evansloan The plugin is still not functional for new users / when resetting data. @kschmanski's screenshot is the same behaviour I'm seeing, and a bunch of clanmates are seeing as well.

**Comment by phife-dawg** [comment]
+1 I am seeing this as well

**Comment by kschmanski** [comment]
This actually looks fixed to me as of yesterday, 2/26.

**Comment by Starnub** [comment]
Still not working for me unfortunately.

**Comment by 25adrian25** [comment]
any update on when this plugin is gonna work again for new people?

**Comment by 3-pm** [comment]
@evansloan bump -- I'd really love to use this plugin :)

**Comment by Tzrt** [comment]
Bumping thread - Evan I can definitely confirm that the assessment that new users can't use the plugin is accurate. I am faced with the same issue as kschmanski above. Would love to be able to use this plugin to flex sub 50 kc shadow!

**Comment by HuffmanJames** [comment]
Can confirm this is still an active issue preventing new users from using the plugin. Needs to be addressed.

**Comment by Jacob-Lasky** [comment]
Adding my voice to this - still an issue for those three new bosses.

**Comment by jebidis** [comment]
Yes this is still an issue, but the plugin still works as @evansloan mentioned in his comment.  The `!log` commands still work and you can still upload your progress to the website.  But to upload your log, you have to go to `settings`->`Collection Log`->`Exporting` and  click the checkbox for `Allow collectionlog.net connections`.

**Comment by Tzrt** [comment]
> Yes this is still an issue, but the plugin still works as @evansloan mentioned in his comment. The `!log` commands still work and you can still upload your progress to the website. But to upload your log, you have to go to `settings`->`Collection Log`->`Exporting` and click the checkbox for `Allow collectionlog.net connections`.

The website does work for affected users, but the !log command does not. All logs will give the 'no collection log data found for user' error in game if you're having this issue.

**Comment by jameshalldev** [comment]
Can confirm this is still an issue for first-time users.

**Comment by dayoshiguy** [comment]
this is still an issue. please fix this I want to use ur plugin.

**Comment by hydraware** [comment]
Can confirm this issue still exists.

**Comment by HuffmanJames** [comment]
Hi, I haven’t done detailed testing but it appears to be working now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 3-pm** [comment]
@HuffmanJames @evansloan 

It's still not working for new users. Just tested again. Nothing has been fixed/ committed for this issue.

**Comment by 3-pm** [comment]
Hey @evansloan, can we get an ETA on this new-user fix? Clearly the site is your priority for commits, but it would be nice to not get ghosted in this issue thread for over 3 months.

**Comment by popekappa** [comment]
Also having this issue!! Would love to see a fix for such a great plugin!

**Comment by popekappa** [comment]
fantastic! Thank you so much!! 😄

**Comment by xDemoN** [comment]
Can confirm this issue is fixed with the newest update.
