### ISSUE TITLE
Plugin is incompatible and requires its author to update

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [evansloan/collection-log#47]
On RuneLite version 1.10.20.3 the plugin version 3.0.2 is incompatible:

<img width="224" alt="image" src="https://github.com/evansloan/collection-log/assets/96475496/a4bb768f-d14d-4586-8bec-9f477eeac4f9">

**Comment by fuzxi** [comment]
3.1.2 fixes this and is on the plugin hub as of ~6 hours ago.
