### ISSUE TITLE
Awakener's Orb not properly tracking # received

### ISSUE THREAD

**Issue by BrianBolti** [evansloan/collection-log#49]
Even if you have more than 1 Orb, all metrics and reporting does not include them into the calculation. 

For context - I have relogged, full closed browser, and reset the plugin. Collection log plugin tracks data fine.

Every time you will report, it will assume as if you've only received one orb.
![image](https://github.com/evansloan/collection-log/assets/148491504/be1b0805-6e26-4656-8298-3061dbd65c89)
![image](https://github.com/evansloan/collection-log/assets/148491504/e86a90eb-0ee1-4e0a-9936-14be0a479f84)

**Comment by peanubnutter** [comment]
Are you sure your collection log is up to date? Check collectionlog.net to make sure. Your leviathan KC is also off (137 vs. 177 in log) so I don't think it's up to date.

**Comment by peanubnutter** [comment]
Also, this is the GitHub for collection log plugin, not collection log luck plugin :)

**Comment by BrianBolti** [comment]
Issue also seems present with chromium ingots :
![image](https://github.com/evansloan/collection-log/assets/148491504/8c88910c-69a8-47cc-aa0d-33095a5b2574)
![image](https://github.com/evansloan/collection-log/assets/148491504/5bbfce96-30d8-4575-82c3-caf595e7faa4)
