### ISSUE TITLE
Clicking the currently opened log section removes all "completed" green highlights

### ISSUE THREAD

**Issue by Nightfirecat** [evansloan/collection-log#6]
To reproduce:

1. Open the collection log (must have at least one "completed" section highlighted green)
2. Click the active section
3. Observe that all green highlights are cleared until a new section/tab is opened

**Comment by evansloan** [comment]
I've been trying to track this one down since highlighting was added. I can't seem to find any event that is triggered when an already open section is clicked on again.

**Comment by Nightfirecat** [comment]
My guess is a widget update is triggered via some script (which doesn't re-trigger WidgetLoaded or a varbit change) which wouldn't be handled. I'll take a look at this tomorrow

**Comment by Nightfirecat** [comment]
Took me an extra day to muster the willpower to look at code, but this seems to be fixed by checking the interface after the log drawing script completes instead of listening for WidgetLoaded.
